### ISSUE TITLE
[FEATURE] Arrays

### ISSUE THREAD

**Issue by tmob03** [ArgosOfIthica/scalu#40]
**Is your feature request related to a problem? Please describe.**
It's time consuming writing scripts that say have a game board, and needing a spot0, spot1, spot2, etc variables. Arrays would make it easier and faster to make these. Just `spot[9] = {0,0,0..etc}` would be a lot easier.

**Describe the solution you'd like**
Arrays be added and defined like the above. Positions would be set like `spot[4] = 72` after the array is declared. If statements would be normal like `if (spot[5] == 2)`
In code, I think it would make sense to just split these into their individual elements, going back to the spot0, spot1, etc variables, but the user wouldn't need to define these. They would just be in the compiled script.

**Additional context**
I'm not sure if arrays could be actually implemented and exist in the compiled script, as I know understand the logic of scalu very well. If they can be, it might be better to do that, just do whichever results in smaller, faster scripts (real arrays or scalu arrays just being compiled into their individual elements)

**Comment by ArgosOfIthica** [comment]
There's a few ways to interpret this request. For simply batching up variable declarations, macros will be well suited. Here's what doing what you want may eventually look like:

```
#def generate i9 range special 0 9 1## /*create a string called i9 using the special range function. Generates "0 1 2 3 4..."*/
#def template create_spot var spot#@ = 0 /*create a template called create_var for generating vars*/ ##
#def generate spot_vars create_spot implode #i9 ## /*create a string called spot_vars with our declarations and implode i9 against it*/

service my_setup{
    #write #spot_vars##
}
```

Then, if you decide you'd like 64 variables instead of 9, it's a very small change.

To emulate real array _semantics_, you would construct something similar, but also include a jump table used by the index of your array.

For array syntax, I'm not sure I'm interested in having arrays as first class constructs, as true array semantics are fairly expensive. In most cases where you'd want arrays, macros would be a more efficient solution.

**Comment by tmob03** [comment]
Neat, okay. When the branch gets merged, please write some documentation because these explanations are very obtuse to me, with no formal computer science teachings. When this happens, I’ll reopen this issue should I have any problems with this macro system,

**Comment by ArgosOfIthica** [comment]
Will do! I definitely don't expect _anyone_ to understand it given a settled on the syntax a week ago. I thought about already having written documentation, but things are still subject to change. The key takeaway is that something like this should end up being a 2/3 line macro.
